def getLogo(int):
	if int == 1:
		print "\n"
		print "88                                                                                                                  " 
		print "88                ,d                                                                  ,d                            " 
		print "88                88                                                                  88                            " 
		print "88  8b,dPPYba,  MM88MMM  ,adPPYba,  8b,dPPYba,   ,adPPYba,   ,adPPYba,  8b,dPPYba,  MM88MMM  ,adPPYba,   8b,dPPYba, " 
		print "88  88P'   `'8a   88    a8P_____88  88P'   'Y8  a8'     ''  a8P_____88  88P'    '8a   88    a8'     '8a  88P'   'Y8 " 
		print "88  88       88   88    8PP'''''''  88          8b          8PP'''''''  88       d8   88    8b       d8  88         " 
		print "88  88       88   88,   '8b,   ,aa  88          '8a,   ,aa  '8b,   ,aa  88b,   ,a8'   88,   '8a,   ,a8'  88         " 
		print "88  88       88   'Y888  `'Ybbd8''  88           `'Ybbd8''   `'Ybbd8''  88`YbbdP''    'Y888  `'YbbdP''   88         " 
		print "                                                                        88                                          " 
		print "                                                                        88                                          " 
		print "                                          						  Man In The Middle ToolKit"
		print "\n" 
	elif int == 2:
		print "\n"
		print " _____       _                          _             "
		print "|_   _|     | |                        | |            "
		print "  | |  _ __ | |_ ___ _ __ ___ ___ _ __ | |_ ___  _ __ "
		print "  | | | '_ \| __/ _ \ '__/ __/ _ \ '_ \| __/ _ \| '__|"
		print " _| |_| | | | ||  __/ | | (_|  __/ |_) | || (_) | |   "
		print "|_____|_| |_|\__\___|_|  \___\___| .__/ \__\___/|_|   "
		print "                                 | |                  "
		print "                                 |_|                  "
		print "                             Man In The Middle ToolKit"                                           
		print "\n"                                                                 
